/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// main.ts
__export(exports, {
  default: () => AnkifyPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var DEFAULT_SETTINGS = {
  apiModel: "deepseek",
  deepseekApiKey: "",
  deepseekApiUrl: "https://api.deepseek.com/v1/chat/completions",
  openaiApiKey: "",
  claudeApiKey: "",
  doubaoApiKey: "",
  doubaoApiUrl: "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
  doubaoModelName: "doubao-1-5-vision-pro-32k-250115",
  customApiUrl: "https://api.example.com/v1/chat/completions",
  customApiKey: "",
  customModelName: "custom-model",
  customApiVersion: "",
  customPrompt: '\u8BF7\u57FA\u4E8E\u4EE5\u4E0B\u5185\u5BB9\u521B\u5EFAAnki\u5361\u7247\uFF0C\u683C\u5F0F\u4E3A"\u95EE\u9898:::\u7B54\u6848"\uFF0C\u6BCF\u4E2A\u5361\u7247\u4E00\u884C\u3002\u63D0\u53D6\u5173\u952E\u6982\u5FF5\u548C\u77E5\u8BC6\u70B9\u3002\n\n',
  visionPrompt: '\u8BF7\u8BC6\u522B\u8FD9\u5F20\u56FE\u7247\u4E2D\u7684\u5185\u5BB9\uFF0C\u5E76\u57FA\u4E8E\u56FE\u7247\u5185\u5BB9\u521B\u5EFAAnki\u5361\u7247\uFF0C\u683C\u5F0F\u4E3A"\u95EE\u9898:::\u7B54\u6848"\uFF0C\u6BCF\u4E2A\u5361\u7247\u4E00\u884C\u3002\u63D0\u53D6\u56FE\u7247\u4E2D\u7684\u5173\u952E\u6982\u5FF5\u548C\u77E5\u8BC6\u70B9\u3002',
  maxImageSize: 1024,
  imageQuality: 0.8,
  insertToDocument: false,
  ankiConnectUrl: "http://127.0.0.1:8765",
  defaultDeck: "Default",
  defaultNoteType: "Basic"
};
var AnkifyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.noteTypeFields = {};
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "generate-anki-cards",
      name: "\u751F\u6210Anki\u5361\u7247",
      editorCallback: (editor, view) => {
        this.processContent(editor, view);
      }
    });
    this.addSettingTab(new AnkifySettingTab(this.app, this));
    this.addRibbonIcon("dice", "Ankify\u9009\u4E2D\u5185\u5BB9", (evt) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view) {
        this.processContent(view.editor, view);
      } else {
        new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2AMarkdown\u6587\u4EF6");
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async invokeAnkiConnect(action, params = {}) {
    const requestBody = {
      action,
      version: 6,
      params
    };
    console.log("\u53D1\u9001Anki Connect\u8BF7\u6C42:", {
      url: this.settings.ankiConnectUrl,
      action,
      params
    });
    const response = await fetch(this.settings.ankiConnectUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });
    if (!response.ok) {
      throw new Error(`Anki Connect\u8BF7\u6C42\u5931\u8D25: ${response.statusText}`);
    }
    const data = await response.json();
    console.log("Anki Connect\u54CD\u5E94:", data);
    if (data.error) {
      throw new Error(`Anki Connect\u9519\u8BEF: ${data.error}`);
    }
    return data.result;
  }
  async getDeckNames() {
    try {
      return await this.invokeAnkiConnect("deckNames");
    } catch (error) {
      console.error("\u83B7\u53D6\u724C\u7EC4\u5217\u8868\u5931\u8D25:", error);
      new import_obsidian.Notice("\u83B7\u53D6Anki\u724C\u7EC4\u5217\u8868\u5931\u8D25\uFF0C\u8BF7\u786E\u4FDDAnki\u5DF2\u542F\u52A8\u4E14\u5B89\u88C5\u4E86Anki Connect\u63D2\u4EF6");
      return [];
    }
  }
  async getNoteTypes() {
    try {
      return await this.invokeAnkiConnect("modelNames");
    } catch (error) {
      console.error("\u83B7\u53D6\u7B14\u8BB0\u7C7B\u578B\u5217\u8868\u5931\u8D25:", error);
      return [];
    }
  }
  parseAnkiCards(text) {
    var _a, _b, _c, _d;
    const cards = [];
    console.log("\u5F00\u59CB\u89E3\u6790Anki\u5361\u7247\uFF0C\u539F\u59CB\u6587\u672C\u957F\u5EA6:", text.length);
    console.log("\u539F\u59CB\u6587\u672C\u524D500\u5B57\u7B26:", text.substring(0, 500));
    const isMultiLineFormat = /Q:.*\nA:.*(\nannotation:.*)?(\ntags:.*)?/i.test(text);
    if (isMultiLineFormat) {
      console.log("\u68C0\u6D4B\u5230\u591A\u884C\u683C\u5F0F\u6570\u636E");
      const cardBlocks = text.split(/\n\s*\n+/).filter((block) => block.trim());
      for (const block of cardBlocks) {
        const lines = block.split("\n").map((line) => line.trim()).filter((line) => line);
        const card = {
          question: "",
          answer: "",
          noteType: this.settings.defaultNoteType,
          originalAnswer: "",
          tags: []
        };
        for (const line of lines) {
          if (line.startsWith("Q:") || line.startsWith("\u95EE:") || line.startsWith("\u95EE\uFF1A")) {
            card.question = line.substring(2).trim();
          } else if (line.startsWith("A:") || line.startsWith("\u7B54:") || line.startsWith("\u7B54\uFF1A")) {
            card.answer = line.substring(2).trim();
            card.originalAnswer = card.answer;
            if (this.containsClozeFormat(card.answer)) {
              card.noteType = "Cloze";
            }
          } else if (line.startsWith("annotation:") || line.startsWith("\u6CE8\u91CA:") || line.startsWith("\u6CE8\u91CA\uFF1A")) {
            card.annotation = line.substring(line.indexOf(":") + 1).trim();
          } else if (line.startsWith("tags:") || line.startsWith("\u6807\u7B7E:") || line.startsWith("\u6807\u7B7E\uFF1A")) {
            const tagsText = line.substring(line.indexOf(":") + 1).trim();
            if (tagsText.includes("#")) {
              const newTags = tagsText.split("#").map((tag) => tag.trim()).filter((tag) => tag.length > 0);
              card.tags = [...card.tags, ...newTags];
            } else {
              const newTags = tagsText.split(/[\s,]+/).map((tag) => tag.trim()).filter((tag) => tag.length > 0);
              card.tags = [...card.tags, ...newTags];
            }
          }
        }
        if (card.question && card.answer) {
          cards.push(card);
        }
      }
    } else {
      const lines = text.split("\n").filter((line) => line.trim());
      if (lines.length === 0) {
        return cards;
      }
      const headerLine = lines[0].trim();
      const isTableFormat = /^Q[\t\s]+A[\t\s]+annotation[\t\s]+tags$/i.test(headerLine);
      if (isTableFormat) {
        console.log("\u68C0\u6D4B\u5230\u8868\u683C\u683C\u5F0F\u6570\u636E");
        for (let i = 1; i < lines.length; i++) {
          const line = lines[i].trim();
          if (!line)
            continue;
          let parts;
          if (line.includes("	")) {
            parts = line.split("	");
          } else {
            parts = line.split(/\s{2,}/);
          }
          if (parts.length >= 2) {
            const card = {
              question: parts[0].trim(),
              answer: parts[1].trim(),
              noteType: this.settings.defaultNoteType,
              originalAnswer: parts[1].trim(),
              tags: []
            };
            if (this.containsClozeFormat(card.answer)) {
              card.noteType = "Cloze";
            }
            if (parts.length >= 3 && parts[2].trim()) {
              card.annotation = parts[2].trim();
            }
            if (parts.length >= 4 && parts[3].trim()) {
              const tagsText = parts[3].trim();
              if (tagsText) {
                if (tagsText.includes("#")) {
                  const tagParts = tagsText.split("#");
                  const newTags = tagParts.map((tag) => tag.trim()).filter((tag) => tag.length > 0);
                  card.tags = [...card.tags, ...newTags];
                } else {
                  const newTags = tagsText.split(/[\s,]+/).map((tag) => tag.trim()).filter((tag) => tag.length > 0);
                  card.tags = [...card.tags, ...newTags];
                }
              }
            }
            cards.push(card);
          }
        }
      } else {
        for (const line of lines) {
          const qaMatch = line.match(/(?:Q:|问[:：])\s*(.*?)\s*(?:A:|答[:：])\s*(.*?)(?:\s*annotation:|注释[:：]|$|\s*tags:|标签[:：])/i);
          if (qaMatch) {
            const card = {
              question: ((_a = qaMatch[1]) == null ? void 0 : _a.trim()) || "",
              answer: ((_b = qaMatch[2]) == null ? void 0 : _b.trim()) || "",
              noteType: this.settings.defaultNoteType,
              originalAnswer: ((_c = qaMatch[2]) == null ? void 0 : _c.trim()) || "",
              tags: []
            };
            if (this.containsClozeFormat(card.answer)) {
              card.noteType = "Cloze";
            }
            const annotationMatch = line.match(/(?:annotation:|注释[:：])\s*(.*?)(?:\s*tags:|标签[:：]|$)/i);
            if (annotationMatch) {
              card.annotation = (_d = annotationMatch[1]) == null ? void 0 : _d.trim();
            }
            const tagsMatch = line.match(/(?:tags:|标签[:：])\s*(.*?)$/i);
            if (tagsMatch && tagsMatch[1]) {
              const newTags = tagsMatch[1].split("#").map((tag) => tag.trim()).filter((tag) => tag.length > 0);
              card.tags = [...card.tags, ...newTags];
            }
            cards.push(card);
          } else {
            const splitLine = line.split(":::");
            if (splitLine.length >= 2) {
              const answer = splitLine[1].trim();
              const card = {
                question: splitLine[0].trim(),
                answer,
                noteType: this.settings.defaultNoteType,
                originalAnswer: answer,
                tags: []
              };
              if (this.containsClozeFormat(card.answer)) {
                card.noteType = "Cloze";
              }
              cards.push(card);
            }
          }
        }
      }
    }
    console.log(`\u89E3\u6790\u51FA ${cards.length} \u5F20\u5361\u7247`, cards);
    return cards;
  }
  async addNotesToAnki(cards, deckName, noteType) {
    if (!deckName || !noteType) {
      throw new Error("\u724C\u7EC4\u540D\u79F0\u548C\u7B14\u8BB0\u7C7B\u578B\u4E0D\u80FD\u4E3A\u7A7A");
    }
    console.log("\u51C6\u5907\u6DFB\u52A0\u5361\u7247\u5230Anki:", {
      deckName,
      noteType,
      cardCount: cards.length,
      firstCard: cards[0]
    });
    const notes = await Promise.all(cards.map(async (card, index) => {
      if (!card.question || !card.answer) {
        throw new Error(`\u5361\u7247\u5185\u5BB9\u4E0D\u5B8C\u6574\uFF1A
\u95EE\u9898\uFF1A${card.question}
\u7B54\u6848\uFF1A${card.answer}`);
      }
      const cardNoteType = card.noteType;
      let fields = {};
      const modelFieldNames = await this.invokeAnkiConnect("modelFieldNames", { modelName: cardNoteType });
      console.log(`\u7B14\u8BB0\u7C7B\u578B ${cardNoteType} \u7684\u5B57\u6BB5\u540D\u79F0:`, modelFieldNames);
      this.noteTypeFields[cardNoteType] = modelFieldNames;
      if (cardNoteType === "Cloze" || cardNoteType === "\u586B\u7A7A\u9898") {
        let mainFieldName;
        let extraFieldName = null;
        if (modelFieldNames.includes("Text")) {
          mainFieldName = "Text";
          if (modelFieldNames.includes("Back Extra")) {
            extraFieldName = "Back Extra";
          } else if (modelFieldNames.includes("Extra")) {
            extraFieldName = "Extra";
          } else if (modelFieldNames.includes("Back")) {
            extraFieldName = "Back";
          }
        } else if (modelFieldNames.includes("\u6B63\u9762")) {
          mainFieldName = "\u6B63\u9762";
          if (modelFieldNames.includes("\u80CC\u9762 \u989D\u5916")) {
            extraFieldName = "\u80CC\u9762 \u989D\u5916";
          } else if (modelFieldNames.includes("\u989D\u5916")) {
            extraFieldName = "\u989D\u5916";
          } else if (modelFieldNames.includes("\u80CC\u9762")) {
            extraFieldName = "\u80CC\u9762";
          }
        } else if (modelFieldNames.includes("Back")) {
          mainFieldName = "Back";
          if (modelFieldNames.includes("Back Extra")) {
            extraFieldName = "Back Extra";
          } else if (modelFieldNames.includes("Extra")) {
            extraFieldName = "Extra";
          }
        } else if (modelFieldNames.length > 0) {
          mainFieldName = modelFieldNames[0];
          for (let i = 1; i < modelFieldNames.length; i++) {
            const field = modelFieldNames[i];
            if (field === "Back Extra" || field === "\u80CC\u9762 \u989D\u5916" || field === "Extra" || field === "\u989D\u5916" || field === "Back" || field === "\u80CC\u9762") {
              extraFieldName = field;
              break;
            }
          }
          if (!extraFieldName && modelFieldNames.length > 1) {
            extraFieldName = modelFieldNames[1];
          }
        } else {
          throw new Error(`\u65E0\u6CD5\u786E\u5B9ACloze\u7B14\u8BB0\u7C7B\u578B\u7684\u5B57\u6BB5`);
        }
        fields = {
          [mainFieldName]: card.answer
        };
        if (extraFieldName && card.annotation) {
          fields[extraFieldName] = card.annotation;
          console.log(`\u5C06\u6CE8\u91CA\u653E\u5165\u989D\u5916\u5B57\u6BB5 ${extraFieldName}:`, card.annotation);
        } else if (card.annotation) {
          fields[mainFieldName] += `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>`;
          console.log(`\u5C06\u6CE8\u91CA\u8FFD\u52A0\u5230\u4E3B\u8981\u5B57\u6BB5 ${mainFieldName}:`, card.annotation);
        }
      } else if (modelFieldNames.includes("Front") && modelFieldNames.includes("Back")) {
        fields = {
          Front: card.question,
          Back: card.answer + (card.annotation ? `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>` : "")
        };
      } else if (modelFieldNames.includes("\u6B63\u9762") && modelFieldNames.includes("\u80CC\u9762")) {
        fields = {
          \u6B63\u9762: card.question,
          \u80CC\u9762: card.answer + (card.annotation ? `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>` : "")
        };
      } else if (modelFieldNames.includes("Text") && modelFieldNames.includes("Extra")) {
        fields = {
          Text: card.question,
          Extra: card.answer + (card.annotation ? `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>` : "")
        };
      } else {
        if (modelFieldNames.length >= 2) {
          fields = {
            [modelFieldNames[0]]: card.question,
            [modelFieldNames[1]]: card.answer + (card.annotation ? `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>` : "")
          };
        } else if (modelFieldNames.length === 1) {
          fields = {
            [modelFieldNames[0]]: card.answer + (card.annotation ? `
<hr>
<span style="color: rgb(143, 53, 8);">${card.annotation}</span>` : "")
          };
        } else {
          throw new Error(`\u65E0\u6CD5\u786E\u5B9A\u7B14\u8BB0\u7C7B\u578B ${cardNoteType} \u7684\u5B57\u6BB5\u6620\u5C04`);
        }
      }
      for (const [key, value] of Object.entries(fields)) {
        if (!value || value.trim() === "") {
          throw new Error(`\u5B57\u6BB5 "${key}" \u4E0D\u80FD\u4E3A\u7A7A`);
        }
      }
      const userTags = (card.tags || []).filter((tag) => tag !== "ankify");
      const finalTags = [...userTags, "ankify"];
      const note = {
        deckName,
        modelName: cardNoteType,
        fields,
        tags: finalTags,
        options: {
          allowDuplicate: false
        }
      };
      console.log(`\u7B2C ${index + 1} \u5F20\u5361\u7247\u7684\u6807\u7B7E:`, finalTags);
      return note;
    }));
    try {
      console.log("\u6B63\u5728\u6DFB\u52A0\u7B14\u8BB0\u5230Anki:", {
        deckName,
        noteType,
        noteCount: notes.length,
        firstNote: notes[0]
      });
      const result = await this.invokeAnkiConnect("addNotes", { notes });
      if (!result || !Array.isArray(result)) {
        throw new Error("Anki Connect\u8FD4\u56DE\u4E86\u65E0\u6548\u7684\u7ED3\u679C");
      }
      const failedNotes = result.filter((id) => id === null);
      if (failedNotes.length > 0) {
        console.warn(`\u6709 ${failedNotes.length} \u5F20\u5361\u7247\u6DFB\u52A0\u5931\u8D25`);
      }
      return result;
    } catch (error) {
      console.error("\u6DFB\u52A0\u7B14\u8BB0\u5931\u8D25:", error);
      throw new Error(`\u6DFB\u52A0\u7B14\u8BB0\u5931\u8D25: ${error.message}`);
    }
  }
  parseImagePath(text) {
    const imageRegex = /!\[([^\]]*)\]\(([^)]+)\)/;
    const match = text.match(imageRegex);
    return match ? match[2] : null;
  }
  async readImageAsBase64(imagePath, currentFilePath) {
    var _a, _b, _c, _d;
    try {
      const vault = this.app.vault;
      const currentFile = this.app.workspace.getActiveFile();
      if (!currentFile) {
        throw new Error("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6");
      }
      console.log("\u5F00\u59CB\u8BFB\u53D6\u56FE\u7247:", {
        \u539F\u59CB\u8DEF\u5F84: imagePath,
        \u5F53\u524D\u6587\u4EF6: currentFile.path,
        \u5F53\u524D\u6587\u4EF6\u76EE\u5F55: (_a = currentFile.parent) == null ? void 0 : _a.path
      });
      let fullPath = imagePath;
      let file = vault.getAbstractFileByPath(imagePath);
      if (!file && !imagePath.startsWith("/")) {
        const currentDir = ((_b = currentFile.parent) == null ? void 0 : _b.path) || "";
        fullPath = currentDir ? `${currentDir}/${imagePath}` : imagePath;
        console.log("\u5C1D\u8BD5\u76F8\u5BF9\u8DEF\u5F84:", fullPath);
        file = vault.getAbstractFileByPath(fullPath);
      }
      if (!file) {
        if (imagePath.startsWith("./")) {
          const cleanPath = imagePath.substring(2);
          const currentDir = ((_c = currentFile.parent) == null ? void 0 : _c.path) || "";
          fullPath = currentDir ? `${currentDir}/${cleanPath}` : cleanPath;
          console.log("\u5C1D\u8BD5\u6E05\u7406\u540E\u7684\u8DEF\u5F84:", fullPath);
          file = vault.getAbstractFileByPath(fullPath);
        }
      }
      if (!file) {
        console.error("\u6240\u6709\u8DEF\u5F84\u5C1D\u8BD5\u5931\u8D25\uFF0Cvault\u6240\u6709\u6587\u4EF6:", vault.getFiles().map((f) => f.path));
        throw new Error(`\u627E\u4E0D\u5230\u56FE\u7247\u6587\u4EF6\u3002
\u5C1D\u8BD5\u7684\u8DEF\u5F84: ${imagePath}, ${fullPath}
\u8BF7\u68C0\u67E5\u56FE\u7247\u8DEF\u5F84\u662F\u5426\u6B63\u786E`);
      }
      const actualPath = file.path;
      console.log("\u6210\u529F\u627E\u5230\u6587\u4EF6:", actualPath);
      const arrayBuffer = await vault.readBinary(file);
      const base64Data = this.arrayBufferToBase64(arrayBuffer);
      const ext = (_d = imagePath.split(".").pop()) == null ? void 0 : _d.toLowerCase();
      const mimeType = this.getMimeType(ext || "");
      console.log("\u56FE\u7247\u8BFB\u53D6\u6210\u529F\uFF0C\u5927\u5C0F:", arrayBuffer.byteLength, "bytes");
      return {
        base64: `data:${mimeType};base64,${base64Data}`,
        actualPath
      };
    } catch (error) {
      console.error("\u8BFB\u53D6\u56FE\u7247\u5931\u8D25:", error);
      throw new Error(`\u8BFB\u53D6\u56FE\u7247\u5931\u8D25: ${error.message}`);
    }
  }
  arrayBufferToBase64(buffer) {
    let binary = "";
    const bytes = new Uint8Array(buffer);
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  getMimeType(ext) {
    const mimeTypes = {
      "png": "image/png",
      "jpg": "image/jpeg",
      "jpeg": "image/jpeg",
      "gif": "image/gif",
      "webp": "image/webp",
      "bmp": "image/bmp"
    };
    return mimeTypes[ext] || "image/png";
  }
  async compressImage(base64Image) {
    return new Promise((resolve, reject) => {
      try {
        const img = new Image();
        img.onload = () => {
          let width = img.width;
          let height = img.height;
          const maxSize = this.settings.maxImageSize;
          if (width > maxSize || height > maxSize) {
            if (width > height) {
              height = height * maxSize / width;
              width = maxSize;
            } else {
              width = width * maxSize / height;
              height = maxSize;
            }
          }
          const canvas = document.createElement("canvas");
          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext("2d");
          if (!ctx) {
            reject(new Error("\u65E0\u6CD5\u521B\u5EFAcanvas\u4E0A\u4E0B\u6587"));
            return;
          }
          ctx.drawImage(img, 0, 0, width, height);
          const compressedBase64 = canvas.toDataURL("image/jpeg", this.settings.imageQuality);
          console.log("\u56FE\u7247\u538B\u7F29\u5B8C\u6210:", {
            \u539F\u59CB\u5C3A\u5BF8: `${img.width}x${img.height}`,
            \u538B\u7F29\u540E\u5C3A\u5BF8: `${width}x${height}`,
            \u539F\u59CB\u5927\u5C0F: Math.round(base64Image.length / 1024) + "KB",
            \u538B\u7F29\u540E\u5927\u5C0F: Math.round(compressedBase64.length / 1024) + "KB"
          });
          resolve(compressedBase64);
        };
        img.onerror = () => {
          reject(new Error("\u56FE\u7247\u52A0\u8F7D\u5931\u8D25"));
        };
        img.src = base64Image;
      } catch (error) {
        reject(error);
      }
    });
  }
  async processContent(editor, view) {
    const selectedText = editor.getSelection();
    if (!selectedText) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u62E9\u8981\u5904\u7406\u7684\u6587\u672C\u5185\u5BB9");
      return;
    }
    const imagePath = this.parseImagePath(selectedText);
    if (imagePath) {
      await this.processImage(imagePath, selectedText, editor, view);
      return;
    }
    let apiKey = "";
    const model = this.settings.apiModel;
    if (model === "deepseek") {
      apiKey = this.settings.deepseekApiKey;
    } else if (model === "openai") {
      apiKey = this.settings.openaiApiKey;
    } else if (model === "claude") {
      apiKey = this.settings.claudeApiKey;
    } else if (model === "doubao") {
      apiKey = this.settings.doubaoApiKey;
    } else if (model === "custom") {
      apiKey = this.settings.customApiKey;
      if (!this.settings.customApiUrl) {
        new import_obsidian.Notice("\u8BF7\u5148\u8BBE\u7F6E\u81EA\u5B9A\u4E49API URL");
        return;
      }
      if (!this.settings.customModelName) {
        new import_obsidian.Notice("\u8BF7\u5148\u8BBE\u7F6E\u81EA\u5B9A\u4E49\u6A21\u578B\u540D\u79F0");
        return;
      }
    }
    if (!apiKey) {
      const modelName = model === "deepseek" ? "DeepSeek" : model === "openai" ? "OpenAI" : model === "claude" ? "Claude" : model === "doubao" ? "\u8C46\u5305" : "\u81EA\u5B9A\u4E49API";
      new import_obsidian.Notice(`\u8BF7\u5148\u8BBE\u7F6E${modelName}\u5BC6\u94A5`);
      return;
    }
    const usedPrompt = this.settings.customPrompt + selectedText;
    new SelectableCardsModal(this.app, [], "", this, editor, usedPrompt, "", selectedText, async () => {
      try {
        const result = await this.callModelAPI(selectedText);
        return { result, cards: this.parseAnkiCards(result) };
      } catch (error) {
        console.error("API\u8C03\u7528\u5931\u8D25:", error);
        throw error;
      }
    }, this.settings.insertToDocument).open();
  }
  async processImage(imagePath, selectedText, editor, view) {
    try {
      const currentFile = this.app.workspace.getActiveFile();
      if (!currentFile) {
        throw new Error("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u4EF6");
      }
      const usedPrompt = this.settings.visionPrompt;
      const imageInfo = `\u539F\u59CB\u8DEF\u5F84: ${imagePath}
\u5F53\u524D\u6587\u4EF6: ${currentFile.path}`;
      new SelectableCardsModal(this.app, [], "", this, editor, usedPrompt, imageInfo, selectedText, async () => {
        try {
          const { base64: base64Image, actualPath } = await this.readImageAsBase64(imagePath, currentFile.path);
          const updatedImageInfo = `\u539F\u59CB\u8DEF\u5F84: ${imagePath}
\u5B9E\u9645\u8BFB\u53D6\u8DEF\u5F84: ${actualPath}
\u5F53\u524D\u6587\u4EF6: ${currentFile.path}`;
          const compressedImage = await this.compressImage(base64Image);
          const result = await this.callVisionAPI(compressedImage);
          return {
            result,
            cards: this.parseAnkiCards(result),
            imageInfo: updatedImageInfo
          };
        } catch (error) {
          console.error("\u56FE\u7247\u8BC6\u522B\u5931\u8D25:", error);
          throw error;
        }
      }, this.settings.insertToDocument).open();
    } catch (error) {
      console.error("\u56FE\u7247\u8BC6\u522B\u5931\u8D25:", error);
      new import_obsidian.Notice("\u56FE\u7247\u8BC6\u522B\u5931\u8D25\uFF1A" + error.message);
    }
  }
  appendResultToDocument(editor, result) {
    const docContent = editor.getValue();
    const newContent = docContent + "\n\n## Anki\u5361\u7247\n\n" + result;
    editor.setValue(newContent);
    new import_obsidian.Notice("Anki\u5361\u7247\u5DF2\u6DFB\u52A0\u5230\u6587\u6863\u672B\u5C3E");
  }
  containsClozeFormat(text) {
    const clozePattern = /\{\{c\d+::[^}]+\}\}/g;
    return clozePattern.test(text);
  }
  async callVisionAPI(base64Image) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k;
    const model = this.settings.apiModel;
    let apiUrl = "";
    let headers = {
      "Content-Type": "application/json"
    };
    let requestBody = {};
    const visionPrompt = this.settings.visionPrompt;
    if (model === "deepseek") {
      apiUrl = this.settings.deepseekApiUrl || "https://api.deepseek.com/v1/chat/completions";
      headers["Authorization"] = `Bearer ${this.settings.deepseekApiKey}`;
      const isV3Api = apiUrl.includes("/v3/");
      if (isV3Api) {
        const base64Data = base64Image.includes("base64,") ? base64Image.split("base64,")[1] : base64Image;
        console.log("DeepSeek V3 API \u56FE\u7247\u8BC6\u522B - base64\u6570\u636E\u957F\u5EA6:", base64Data.length);
        console.log("DeepSeek V3 API \u56FE\u7247\u8BC6\u522B - base64\u524D100\u5B57\u7B26:", base64Data.substring(0, 100));
        requestBody = {
          model_version: "v3.0-pro",
          prompt: visionPrompt,
          image_url: `data:image/jpeg;base64,${base64Data}`,
          temperature: 0.7,
          response_format: "text"
        };
        console.log("DeepSeek V3 API \u8BF7\u6C42\u4F53\uFF08\u4E0D\u542B\u56FE\u7247\u6570\u636E\uFF09:", {
          model_version: requestBody.model_version,
          temperature: requestBody.temperature,
          prompt: requestBody.prompt.substring(0, 100) + "..."
        });
      } else {
        const base64Data = base64Image.includes("base64,") ? base64Image.split("base64,")[1] : base64Image;
        console.log("DeepSeek V1 API \u56FE\u7247\u8BC6\u522B - base64\u6570\u636E\u957F\u5EA6:", base64Data.length);
        console.log("DeepSeek V1 API \u56FE\u7247\u8BC6\u522B - base64\u524D100\u5B57\u7B26:", base64Data.substring(0, 100));
        const contentJson = JSON.stringify([
          {
            type: "text",
            text: visionPrompt
          },
          {
            type: "image",
            image: {
              data: base64Data,
              format: "base64"
            }
          }
        ]);
        requestBody = {
          model: "deepseek-chat",
          messages: [
            {
              role: "user",
              content: contentJson
            }
          ],
          temperature: 0.7
        };
        console.log("DeepSeek V1 API \u8BF7\u6C42\u4F53\uFF08\u4E0D\u542B\u56FE\u7247\u6570\u636E\uFF09:", {
          model: requestBody.model,
          temperature: requestBody.temperature,
          contentLength: contentJson.length
        });
      }
    } else if (model === "openai") {
      apiUrl = "https://api.openai.com/v1/chat/completions";
      headers["Authorization"] = `Bearer ${this.settings.openaiApiKey}`;
      requestBody = {
        model: "gpt-4-vision-preview",
        messages: [
          {
            role: "user",
            content: [
              {
                type: "text",
                text: visionPrompt
              },
              {
                type: "image_url",
                image_url: {
                  url: base64Image
                }
              }
            ]
          }
        ],
        max_tokens: 1e3,
        temperature: 0.7
      };
    } else if (model === "claude") {
      apiUrl = "https://api.anthropic.com/v1/messages";
      headers["x-api-key"] = this.settings.claudeApiKey;
      headers["anthropic-version"] = "2023-06-01";
      const imageDataMatch = base64Image.match(/data:(image\/\w+);base64,(.+)/);
      const mediaType = imageDataMatch ? imageDataMatch[1] : "image/png";
      const imageData = imageDataMatch ? imageDataMatch[2] : base64Image;
      requestBody = {
        model: "claude-3-haiku-20240307",
        messages: [
          {
            role: "user",
            content: [
              {
                type: "image",
                source: {
                  type: "base64",
                  media_type: mediaType,
                  data: imageData
                }
              },
              {
                type: "text",
                text: visionPrompt
              }
            ]
          }
        ],
        max_tokens: 1e3,
        temperature: 0.7
      };
    } else if (model === "custom") {
      apiUrl = this.settings.customApiUrl;
      headers["Authorization"] = `Bearer ${this.settings.customApiKey}`;
      if (this.settings.customApiVersion) {
        headers["api-version"] = this.settings.customApiVersion;
      }
      requestBody = {
        model: this.settings.customModelName,
        messages: [
          {
            role: "user",
            content: [
              {
                type: "text",
                text: visionPrompt
              },
              {
                type: "image_url",
                image_url: {
                  url: base64Image
                }
              }
            ]
          }
        ],
        temperature: 0.7
      };
    } else if (model === "doubao") {
      apiUrl = this.settings.doubaoApiUrl;
      headers["Authorization"] = `Bearer ${this.settings.doubaoApiKey}`;
      requestBody = {
        model: this.settings.doubaoModelName,
        messages: [
          {
            role: "user",
            content: [
              {
                type: "image_url",
                image_url: {
                  url: base64Image
                }
              },
              {
                type: "text",
                text: visionPrompt
              }
            ]
          }
        ]
      };
    } else {
      throw new Error("\u4E0D\u652F\u6301\u7684\u6A21\u578B\u7C7B\u578B");
    }
    const startTime = Date.now();
    const response = await fetch(apiUrl, {
      method: "POST",
      headers,
      body: JSON.stringify(requestBody)
    });
    if (!response.ok) {
      const errorText = await response.text();
      console.error("API \u9519\u8BEF\u54CD\u5E94:", errorText);
      let errorMessage = `\u8BF7\u6C42\u5931\u8D25: HTTP ${response.status}`;
      try {
        const errorData = JSON.parse(errorText);
        errorMessage = ((_a = errorData.error) == null ? void 0 : _a.message) || errorData.message || errorText;
      } catch (e) {
        errorMessage = errorText || `HTTP ${response.status} ${response.statusText}`;
      }
      throw new Error(errorMessage);
    }
    const responseText = await response.text();
    if (!responseText || responseText.trim() === "") {
      throw new Error("API \u8FD4\u56DE\u7A7A\u54CD\u5E94");
    }
    console.log("API \u539F\u59CB\u54CD\u5E94:", responseText.substring(0, 500));
    let data;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      console.error("JSON \u89E3\u6790\u5931\u8D25\uFF0C\u539F\u59CB\u54CD\u5E94:", responseText);
      throw new Error(`API \u8FD4\u56DE\u65E0\u6548 JSON \u683C\u5F0F: ${responseText.substring(0, 200)}`);
    }
    const endTime = Date.now();
    console.log(`${model.toUpperCase()} Vision API\u54CD\u5E94\u65F6\u95F4: ${endTime - startTime}ms`);
    let result = "";
    if (model === "deepseek") {
      if (apiUrl.includes("/v3/")) {
        result = data.response || data.text || data.content || data.result || data.output || data.generated_text || "\u65E0\u6CD5\u8BC6\u522B\u56FE\u7247\u5185\u5BB9";
      } else {
        result = ((_c = (_b = data.choices[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "\u65E0\u6CD5\u8BC6\u522B\u56FE\u7247\u5185\u5BB9";
      }
    } else if (model === "openai") {
      result = ((_e = (_d = data.choices[0]) == null ? void 0 : _d.message) == null ? void 0 : _e.content) || "\u65E0\u6CD5\u8BC6\u522B\u56FE\u7247\u5185\u5BB9";
    } else if (model === "claude") {
      result = ((_f = data.content[0]) == null ? void 0 : _f.text) || "\u65E0\u6CD5\u8BC6\u522B\u56FE\u7247\u5185\u5BB9";
    } else if (model === "doubao") {
      result = ((_h = (_g = data.choices[0]) == null ? void 0 : _g.message) == null ? void 0 : _h.content) || "\u65E0\u6CD5\u8BC6\u522B\u56FE\u7247\u5185\u5BB9";
    } else if (model === "custom") {
      if (data.choices && ((_j = (_i = data.choices[0]) == null ? void 0 : _i.message) == null ? void 0 : _j.content)) {
        result = data.choices[0].message.content;
      } else if (data.content && ((_k = data.content[0]) == null ? void 0 : _k.text)) {
        result = data.content[0].text;
      } else if (data.response) {
        result = data.response;
      } else if (data.text || data.content || data.result || data.output || data.generated_text) {
        result = data.text || data.content || data.result || data.output || data.generated_text;
      } else {
        console.warn("\u65E0\u6CD5\u4ECEAPI\u54CD\u5E94\u4E2D\u63D0\u53D6\u5185\u5BB9\uFF0C\u8FD4\u56DE\u5B8C\u6574\u54CD\u5E94:", data);
        result = JSON.stringify(data, null, 2);
      }
    }
    return result;
  }
  async callModelAPI(content) {
    var _a, _b, _c, _d, _e, _f, _g;
    const prompt = this.settings.customPrompt + content;
    const startTime = Date.now();
    const model = this.settings.apiModel;
    let apiUrl = "";
    let headers = {
      "Content-Type": "application/json"
    };
    let requestBody = {};
    if (model === "deepseek") {
      apiUrl = "https://api.deepseek.com/v1/chat/completions";
      headers["Authorization"] = `Bearer ${this.settings.deepseekApiKey}`;
      requestBody = {
        model: "deepseek-chat",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.7
      };
    } else if (model === "openai") {
      apiUrl = "https://api.openai.com/v1/chat/completions";
      headers["Authorization"] = `Bearer ${this.settings.openaiApiKey}`;
      requestBody = {
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.7
      };
    } else if (model === "claude") {
      apiUrl = "https://api.anthropic.com/v1/messages";
      headers["x-api-key"] = this.settings.claudeApiKey;
      headers["anthropic-version"] = "2023-06-01";
      requestBody = {
        model: "claude-3-haiku-20240307",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ],
        max_tokens: 1e3,
        temperature: 0.7
      };
    } else if (model === "doubao") {
      apiUrl = this.settings.doubaoApiUrl;
      headers["Authorization"] = `Bearer ${this.settings.doubaoApiKey}`;
      requestBody = {
        model: this.settings.doubaoModelName,
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      };
    } else if (model === "custom") {
      apiUrl = this.settings.customApiUrl;
      headers["Authorization"] = `Bearer ${this.settings.customApiKey}`;
      if (this.settings.customApiVersion) {
        headers["api-version"] = this.settings.customApiVersion;
      }
      if (apiUrl.includes("openai")) {
        requestBody = {
          model: this.settings.customModelName,
          messages: [
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.7
        };
      } else if (apiUrl.includes("anthropic")) {
        requestBody = {
          model: this.settings.customModelName,
          messages: [
            {
              role: "user",
              content: prompt
            }
          ],
          max_tokens: 1e3,
          temperature: 0.7
        };
      } else {
        requestBody = {
          model: this.settings.customModelName,
          messages: [
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.7
        };
      }
    } else {
      throw new Error("\u4E0D\u652F\u6301\u7684\u6A21\u578B\u7C7B\u578B");
    }
    const response = await fetch(apiUrl, {
      method: "POST",
      headers,
      body: JSON.stringify(requestBody)
    });
    if (!response.ok) {
      const errorText = await response.text();
      console.error("API \u9519\u8BEF\u54CD\u5E94:", errorText);
      let errorMessage = `\u8BF7\u6C42\u5931\u8D25: HTTP ${response.status}`;
      try {
        const errorData = JSON.parse(errorText);
        errorMessage = ((_a = errorData.error) == null ? void 0 : _a.message) || errorData.message || errorText;
      } catch (e) {
        errorMessage = errorText || `HTTP ${response.status} ${response.statusText}`;
      }
      throw new Error(errorMessage);
    }
    const responseText = await response.text();
    if (!responseText || responseText.trim() === "") {
      throw new Error("API \u8FD4\u56DE\u7A7A\u54CD\u5E94");
    }
    console.log("API \u539F\u59CB\u54CD\u5E94:", responseText.substring(0, 500));
    let data;
    try {
      data = JSON.parse(responseText);
    } catch (e) {
      console.error("JSON \u89E3\u6790\u5931\u8D25\uFF0C\u539F\u59CB\u54CD\u5E94:", responseText);
      throw new Error(`API \u8FD4\u56DE\u65E0\u6548 JSON \u683C\u5F0F: ${responseText.substring(0, 200)}`);
    }
    const endTime = Date.now();
    console.log(`${model.toUpperCase()} API\u54CD\u5E94\u65F6\u95F4: ${endTime - startTime}ms`);
    let result = "";
    if (model === "deepseek" || model === "openai" || model === "doubao") {
      result = ((_c = (_b = data.choices[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "\u65E0\u6CD5\u751F\u6210\u5361\u7247\u5185\u5BB9";
    } else if (model === "claude") {
      result = ((_d = data.content[0]) == null ? void 0 : _d.text) || "\u65E0\u6CD5\u751F\u6210\u5361\u7247\u5185\u5BB9";
    } else if (model === "custom") {
      if (data.choices && ((_f = (_e = data.choices[0]) == null ? void 0 : _e.message) == null ? void 0 : _f.content)) {
        result = data.choices[0].message.content;
      } else if (data.content && ((_g = data.content[0]) == null ? void 0 : _g.text)) {
        result = data.content[0].text;
      } else if (data.response) {
        result = data.response;
      } else if (data.text || data.content || data.result || data.output || data.generated_text) {
        result = data.text || data.content || data.result || data.output || data.generated_text;
      } else {
        console.warn("\u65E0\u6CD5\u4ECEAPI\u54CD\u5E94\u4E2D\u63D0\u53D6\u5185\u5BB9\uFF0C\u8FD4\u56DE\u5B8C\u6574\u54CD\u5E94:", data);
        result = JSON.stringify(data, null, 2);
      }
    }
    return result;
  }
};
var SelectableCardsModal = class extends import_obsidian.Modal {
  constructor(app, cards, rawResult, plugin, editor, usedPrompt = "", imageInfo = "", selectedContent = "", apiCallFn = null, insertToDocument = false) {
    super(app);
    this.cards = cards;
    this.rawResult = rawResult;
    this.plugin = plugin;
    this.editor = editor;
    this.selectedCards = cards.map(() => true);
    this.deckName = plugin.settings.defaultDeck;
    this.noteType = plugin.settings.defaultNoteType;
    this.usedPrompt = usedPrompt;
    this.imageInfo = imageInfo;
    this.selectedContent = selectedContent;
    this.apiCallFn = apiCallFn;
    this.insertToDocument = insertToDocument;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.modalEl.style.position = "fixed";
    this.modalEl.style.top = "50%";
    this.modalEl.style.left = "50%";
    this.modalEl.style.transform = "translate(-50%, -50%)";
    this.modalEl.style.width = "80%";
    this.modalEl.style.maxWidth = "800px";
    this.modalEl.style.maxHeight = "80vh";
    this.modalEl.style.overflow = "auto";
    this.loadContent();
  }
  async loadContent() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Anki\u5361\u7247\u751F\u6210" });
    this.addRequestInfo(contentEl);
    const loadingContainer = contentEl.createDiv({ cls: "ankify-loading-container" });
    loadingContainer.style.textAlign = "center";
    loadingContainer.style.padding = "20px";
    const loadingSpinner = loadingContainer.createEl("div", { cls: "ankify-loading-spinner" });
    loadingSpinner.style.fontSize = "24px";
    loadingSpinner.style.marginBottom = "10px";
    loadingSpinner.textContent = "\u23F3";
    const loadingText = loadingContainer.createEl("div", { text: "\u6B63\u5728\u751F\u6210Anki\u5361\u7247\uFF0C\u8BF7\u7A0D\u5019..." });
    loadingText.style.fontSize = "14px";
    loadingText.style.color = "#666";
    let imageInfoEl = null;
    if (this.apiCallFn) {
      try {
        const apiResult = await this.apiCallFn();
        this.rawResult = apiResult.result;
        this.cards = apiResult.cards;
        this.selectedCards = this.cards.map(() => true);
        if (apiResult.imageInfo) {
          this.imageInfo = apiResult.imageInfo;
        }
        loadingContainer.remove();
        if (this.insertToDocument) {
          this.appendResultToDocument(this.editor, this.rawResult);
          this.close();
          return;
        }
        await this.renderCards(contentEl);
        const existingRequestInfo = contentEl.querySelector(".ankify-request-info");
        if (existingRequestInfo) {
          existingRequestInfo.remove();
        }
        this.addRequestInfo(contentEl);
      } catch (error) {
        loadingContainer.remove();
        contentEl.createEl("p", {
          text: `\u751F\u6210\u5931\u8D25: ${error.message}`,
          cls: "ankify-error"
        }).style.color = "red";
        const existingRequestInfo = contentEl.querySelector(".ankify-request-info");
        if (existingRequestInfo) {
          existingRequestInfo.remove();
        }
        this.addRequestInfo(contentEl);
      }
    } else {
      loadingContainer.remove();
      await this.renderCards(contentEl);
      const existingRequestInfo = contentEl.querySelector(".ankify-request-info");
      if (existingRequestInfo) {
        existingRequestInfo.remove();
      }
      this.addRequestInfo(contentEl);
    }
  }
  async renderCards(contentEl) {
    if (this.cards.length === 0) {
      contentEl.createEl("p", {
        text: "\u672A\u80FD\u89E3\u6790\u51FA\u6709\u6548\u7684Anki\u5361\u7247\uFF0C\u8BF7\u68C0\u67E5\u751F\u6210\u7ED3\u679C\u683C\u5F0F\u3002"
      });
      const rawResultEl = contentEl.createDiv({ cls: "ankify-raw-result" });
      const textAreaEl = rawResultEl.createEl("textarea", {
        cls: "ankify-editable-result",
        text: this.rawResult
      });
      textAreaEl.style.width = "100%";
      textAreaEl.style.height = "100px";
      const buttonContainer2 = contentEl.createDiv({
        cls: "ankify-button-container"
      });
      const copyButton2 = buttonContainer2.createEl("button", {
        text: "\u590D\u5236\u5185\u5BB9"
      });
      copyButton2.addEventListener("click", () => {
        navigator.clipboard.writeText(textAreaEl.value);
        new import_obsidian.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
      });
      const insertButton2 = buttonContainer2.createEl("button", {
        text: "\u63D2\u5165\u5230\u6587\u6863"
      });
      insertButton2.addEventListener("click", () => {
        const docContent = this.editor.getValue();
        const newContent = docContent + "\n\n## Anki\u5361\u7247\n\n" + textAreaEl.value;
        this.editor.setValue(newContent);
        new import_obsidian.Notice("\u5185\u5BB9\u5DF2\u6DFB\u52A0\u5230\u6587\u6863\u672B\u5C3E");
        this.close();
      });
      this.addRequestInfo(contentEl);
      return;
    }
    const ankiSettingsEl = contentEl.createDiv({ cls: "ankify-anki-settings" });
    let decks = [];
    try {
      decks = await this.plugin.getDeckNames();
    } catch (error) {
      ankiSettingsEl.createEl("p", {
        cls: "ankify-error",
        text: "\u65E0\u6CD5\u8FDE\u63A5\u5230Anki\u3002\u8BF7\u786E\u4FDDAnki\u5DF2\u7ECF\u542F\u52A8\uFF0C\u4E14\u5DF2\u5B89\u88C5Anki Connect\u63D2\u4EF6\u3002"
      });
    }
    const deckContainer = ankiSettingsEl.createDiv({
      cls: "ankify-setting-item"
    });
    deckContainer.createEl("label", { text: "\u9009\u62E9\u724C\u7EC4\uFF1A" });
    this.deckSelect = deckContainer.createEl("select");
    if (decks.length > 0) {
      decks.forEach((deck) => {
        const option = this.deckSelect.createEl("option", {
          value: deck,
          text: deck
        });
        if (deck === this.plugin.settings.defaultDeck) {
          option.selected = true;
          this.deckName = deck;
        }
      });
    } else {
      this.deckSelect.createEl("option", {
        value: this.deckName,
        text: this.deckName
      });
    }
    this.deckSelect.addEventListener("change", () => {
      this.deckName = this.deckSelect.value;
    });
    const noteTypes = await this.plugin.getNoteTypes();
    const noteTypeContainer = ankiSettingsEl.createDiv({
      cls: "ankify-setting-item"
    });
    noteTypeContainer.createEl("label", { text: "\u7B14\u8BB0\u7C7B\u578B\uFF1A" });
    this.noteTypeSelect = noteTypeContainer.createEl("select");
    if (noteTypes.length > 0) {
      noteTypes.forEach((type) => {
        const option = this.noteTypeSelect.createEl("option", {
          value: type,
          text: type
        });
        if (type === this.plugin.settings.defaultNoteType) {
          option.selected = true;
          this.noteType = type;
        }
      });
    } else {
      const basicTypes = [
        "Basic",
        "Basic (and reversed card)",
        "Cloze",
        "Basic (optional reversed card)"
      ];
      basicTypes.forEach((type) => {
        const option = this.noteTypeSelect.createEl("option", {
          value: type,
          text: type
        });
        if (type === this.plugin.settings.defaultNoteType) {
          option.selected = true;
          this.noteType = type;
        }
      });
    }
    this.noteTypeSelect.addEventListener("change", () => {
      this.noteType = this.noteTypeSelect.value;
    });
    const cardsContainer = contentEl.createDiv({
      cls: "ankify-cards-container"
    });
    const selectAllContainer = cardsContainer.createDiv({
      cls: "ankify-select-all"
    });
    const selectAllCheckbox = selectAllContainer.createEl("input", {
      type: "checkbox"
    });
    selectAllCheckbox.checked = true;
    selectAllContainer.createEl("label", { text: "\u5168\u9009/\u5168\u4E0D\u9009" });
    selectAllCheckbox.addEventListener("change", () => {
      this.selectedCards = this.selectedCards.map(() => selectAllCheckbox.checked);
      this.updateCardSelectionDisplay();
    });
    const cardsListEl = cardsContainer.createDiv({ cls: "ankify-cards-list" });
    const availableNoteTypes = noteTypes.length > 0 ? noteTypes : [
      "Basic",
      "Basic (and reversed card)",
      "Cloze",
      "Basic (optional reversed card)"
    ];
    this.cards.forEach((card, index) => {
      const cardEl = cardsListEl.createDiv({ cls: "ankify-card" });
      const checkboxContainer = cardEl.createDiv({
        cls: "ankify-card-checkbox"
      });
      const checkbox = checkboxContainer.createEl("input", {
        type: "checkbox",
        attr: { id: `card-checkbox-${index}` }
      });
      checkbox.checked = this.selectedCards[index];
      checkbox.addEventListener("change", () => {
        this.selectedCards[index] = checkbox.checked;
      });
      const cardContent = cardEl.createDiv({ cls: "ankify-card-content" });
      const questionEl = cardContent.createDiv({ cls: "ankify-card-question" });
      questionEl.createEl("strong", { text: "\u95EE\u9898: " });
      const questionInput = questionEl.createEl("input", {
        cls: "ankify-card-input",
        type: "text",
        value: card.question
      });
      questionInput.addEventListener("change", () => {
        this.cards[index].question = questionInput.value;
      });
      const answerEl = cardContent.createDiv({ cls: "ankify-card-answer" });
      answerEl.createEl("strong", { text: "\u7B54\u6848: " });
      const answerInput = answerEl.createEl("input", {
        cls: "ankify-card-input",
        type: "text",
        value: card.answer
      });
      answerInput.addEventListener("change", () => {
        this.cards[index].answer = answerInput.value;
      });
      const noteTypeContainer2 = cardContent.createDiv({ cls: "ankify-card-note-type" });
      noteTypeContainer2.createEl("strong", { text: "\u7B14\u8BB0\u7C7B\u578B: " });
      const noteTypeSelect = noteTypeContainer2.createEl("select");
      noteTypeSelect.style.marginLeft = "5px";
      availableNoteTypes.forEach((type) => {
        const option = noteTypeSelect.createEl("option", {
          value: type,
          text: type
        });
        if (type === card.noteType) {
          option.selected = true;
        }
      });
      noteTypeSelect.addEventListener("change", () => {
        const newNoteType = noteTypeSelect.value;
        const oldNoteType = card.noteType;
        card.noteType = newNoteType;
        if (newNoteType === "Cloze") {
          card.answer = card.originalAnswer;
          answerInput.value = card.answer;
        } else if (oldNoteType === "Cloze" && newNoteType !== "Cloze") {
          card.answer = card.answer.replace(/\{\{c\d+::([^}]+)\}\}/g, "$1");
          answerInput.value = card.answer;
        }
      });
      if (card.annotation) {
        const annotationEl = cardContent.createDiv({
          cls: "ankify-card-annotation"
        });
        annotationEl.createEl("strong", { text: "\u6CE8\u91CA: " });
        const annotationInput = annotationEl.createEl("input", {
          cls: "ankify-card-input",
          type: "text",
          value: card.annotation
        });
        annotationInput.addEventListener("change", () => {
          this.cards[index].annotation = annotationInput.value;
        });
      }
      const tagsEl = cardContent.createDiv({ cls: "ankify-card-tags" });
      tagsEl.createEl("strong", { text: "\u6807\u7B7E: " });
      const tagsInput = tagsEl.createEl("input", {
        cls: "ankify-card-input",
        type: "text",
        value: (card.tags || []).join(" "),
        placeholder: "\u8F93\u5165\u6807\u7B7E\uFF0C\u7528\u7A7A\u683C\u5206\u9694"
      });
      tagsInput.addEventListener("change", () => {
        this.cards[index].tags = tagsInput.value.split(/\s+/).map((tag) => tag.trim()).filter((tag) => tag.length > 0);
      });
    });
    const batchTagsContainer = contentEl.createDiv({
      cls: "ankify-batch-tags-container"
    });
    batchTagsContainer.style.marginTop = "20px";
    const batchTagsHeader = batchTagsContainer.createEl("div");
    batchTagsHeader.style.display = "flex";
    batchTagsHeader.style.justifyContent = "space-between";
    batchTagsHeader.style.alignItems = "center";
    batchTagsHeader.style.cursor = "pointer";
    batchTagsHeader.style.padding = "10px";
    batchTagsHeader.style.backgroundColor = "var(--background-secondary)";
    batchTagsHeader.style.border = "1px solid var(--border-color)";
    batchTagsHeader.style.borderRadius = "4px";
    batchTagsHeader.style.color = "var(--text-normal)";
    const batchTagsTitle = batchTagsHeader.createEl("h4", { text: "\u6279\u91CF\u66FF\u6362\u6807\u7B7E" });
    batchTagsTitle.style.margin = "0";
    batchTagsTitle.style.fontSize = "14px";
    batchTagsTitle.style.color = "var(--text-normal)";
    const batchTagsToggle = batchTagsHeader.createEl("span", { text: "\u25BC" });
    batchTagsToggle.style.color = "var(--text-muted)";
    const batchTagsContent = batchTagsContainer.createEl("div");
    batchTagsContent.style.display = "none";
    batchTagsContent.style.padding = "15px";
    batchTagsContent.style.backgroundColor = "var(--background-secondary)";
    batchTagsContent.style.border = "1px solid var(--border-color)";
    batchTagsContent.style.borderTop = "none";
    batchTagsContent.style.borderRadius = "0 0 4px 4px";
    batchTagsContent.style.color = "var(--text-normal)";
    batchTagsHeader.addEventListener("click", () => {
      if (batchTagsContent.style.display === "none") {
        batchTagsContent.style.display = "block";
        batchTagsToggle.textContent = "\u25B2";
      } else {
        batchTagsContent.style.display = "none";
        batchTagsToggle.textContent = "\u25BC";
      }
    });
    const oldTagInput = batchTagsContent.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165\u8981\u66FF\u6362\u7684\u6807\u7B7E"
    });
    oldTagInput.style.width = "100%";
    oldTagInput.style.padding = "8px";
    oldTagInput.style.marginBottom = "10px";
    oldTagInput.style.border = "1px solid var(--border-color)";
    oldTagInput.style.borderRadius = "4px";
    oldTagInput.style.backgroundColor = "var(--background-primary)";
    oldTagInput.style.color = "var(--text-normal)";
    const newTagInput = batchTagsContent.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165\u65B0\u7684\u6807\u7B7E"
    });
    newTagInput.style.width = "100%";
    newTagInput.style.padding = "8px";
    newTagInput.style.marginBottom = "10px";
    newTagInput.style.border = "1px solid var(--border-color)";
    newTagInput.style.borderRadius = "4px";
    newTagInput.style.backgroundColor = "var(--background-primary)";
    newTagInput.style.color = "var(--text-normal)";
    const replaceAllCheckbox = batchTagsContent.createEl("input", {
      type: "checkbox",
      id: "replace-all-tags"
    });
    const replaceAllLabel = batchTagsContent.createEl("label", {
      text: " \u6574\u4E2A\u66FF\u6362\uFF08\u66FF\u6362\u6240\u6709\u6807\u7B7E\uFF09",
      for: "replace-all-tags"
    });
    replaceAllLabel.style.marginBottom = "15px";
    replaceAllLabel.style.display = "block";
    replaceAllLabel.style.color = "var(--text-normal)";
    const replaceTagsButton = batchTagsContent.createEl("button", {
      text: "\u66FF\u6362\u6807\u7B7E"
    });
    replaceTagsButton.style.padding = "8px 16px";
    replaceTagsButton.style.backgroundColor = "var(--interactive-accent)";
    replaceTagsButton.style.color = "var(--text-on-accent)";
    replaceTagsButton.style.border = "none";
    replaceTagsButton.style.borderRadius = "4px";
    replaceTagsButton.style.cursor = "pointer";
    replaceTagsButton.addEventListener("click", () => {
      const oldTag = oldTagInput.value.trim();
      const newTag = newTagInput.value.trim();
      const replaceAll = replaceAllCheckbox.checked;
      let changes = 0;
      this.cards.forEach((card, index) => {
        if (replaceAll) {
          const newTags = newTag.split(/\s+/).map((tag) => tag.trim()).filter((tag) => tag.length > 0);
          this.cards[index].tags = [...newTags];
          changes++;
        } else {
          if (oldTag) {
            const updatedTags = (card.tags || []).map((tag) => tag === oldTag ? newTag : tag).filter((tag) => tag.length > 0);
            if (JSON.stringify(updatedTags) !== JSON.stringify(card.tags)) {
              this.cards[index].tags = updatedTags;
              changes++;
            }
          }
        }
      });
      const allTagsInputs = contentEl.querySelectorAll(".ankify-card-tags input");
      allTagsInputs.forEach((input, index) => {
        var _a;
        input.value = ((_a = this.cards[index].tags) == null ? void 0 : _a.join(" ")) || "";
      });
      if (changes > 0) {
        if (replaceAll) {
          new import_obsidian.Notice(`\u5DF2\u66FF\u6362\u6240\u6709\u5361\u7247\u7684\u6807\u7B7E\u4E3A: ${newTag || "(\u7A7A)"}`);
        } else {
          new import_obsidian.Notice(`\u5DF2\u5C06\u6807\u7B7E "${oldTag}" \u66FF\u6362\u4E3A "${newTag}"\uFF0C\u5171\u4FEE\u6539\u4E86 ${changes} \u5F20\u5361\u7247`);
        }
      } else {
        new import_obsidian.Notice("\u6CA1\u6709\u8FDB\u884C\u4EFB\u4F55\u66FF\u6362");
      }
    });
    const buttonContainer = contentEl.createDiv({
      cls: "ankify-button-container"
    });
    const addToAnkiButton = buttonContainer.createEl("button", {
      cls: "ankify-primary-button",
      text: "\u6DFB\u52A0\u5230Anki"
    });
    addToAnkiButton.addEventListener("click", async () => {
      const selectedCardsList = this.cards.filter((_, index) => this.selectedCards[index]);
      if (selectedCardsList.length === 0) {
        new import_obsidian.Notice("\u8BF7\u81F3\u5C11\u9009\u62E9\u4E00\u5F20\u5361\u7247");
        return;
      }
      try {
        const loadingNotice = new import_obsidian.Notice("\u6B63\u5728\u6DFB\u52A0\u5361\u7247\u5230Anki...", 0);
        const result = await this.plugin.addNotesToAnki(selectedCardsList, this.deckName, this.noteType);
        this.plugin.settings.defaultDeck = this.deckName;
        this.plugin.settings.defaultNoteType = this.noteType;
        await this.plugin.saveSettings();
        const successCount = result.filter((id) => id !== null).length;
        loadingNotice.hide();
        new import_obsidian.Notice(`\u6210\u529F\u6DFB\u52A0 ${successCount}/${selectedCardsList.length} \u5F20\u5361\u7247\u5230Anki`);
        this.close();
      } catch (error) {
        new import_obsidian.Notice(`\u6DFB\u52A0\u5361\u7247\u5931\u8D25: ${error.message}`);
      }
    });
    const copyButton = buttonContainer.createEl("button", {
      text: "\u590D\u5236\u5168\u90E8\u5185\u5BB9"
    });
    copyButton.addEventListener("click", () => {
      navigator.clipboard.writeText(this.rawResult);
      new import_obsidian.Notice("\u5DF2\u590D\u5236\u539F\u59CB\u5185\u5BB9\u5230\u526A\u8D34\u677F");
    });
    const insertButton = buttonContainer.createEl("button", {
      text: "\u63D2\u5165\u5230\u6587\u6863"
    });
    insertButton.addEventListener("click", () => {
      const docContent = this.editor.getValue();
      const newContent = docContent + "\n\n## Anki\u5361\u7247\n\n" + this.rawResult;
      this.editor.setValue(newContent);
      new import_obsidian.Notice("\u5185\u5BB9\u5DF2\u6DFB\u52A0\u5230\u6587\u6863\u672B\u5C3E");
      this.close();
    });
  }
  appendResultToDocument(editor, result) {
    const docContent = editor.getValue();
    const newContent = docContent + "\n\n## Anki\u5361\u7247\n\n" + result;
    editor.setValue(newContent);
    new import_obsidian.Notice("Anki\u5361\u7247\u5DF2\u6DFB\u52A0\u5230\u6587\u6863\u672B\u5C3E");
  }
  updateCardSelectionDisplay() {
    this.selectedCards.forEach((isSelected, index) => {
      const checkbox = document.getElementById(`card-checkbox-${index}`);
      if (checkbox) {
        checkbox.checked = isSelected;
      }
    });
  }
  addRequestInfo(contentEl) {
    const requestInfoContainer = contentEl.createDiv({ cls: "ankify-request-info" });
    requestInfoContainer.style.marginTop = "20px";
    const header = requestInfoContainer.createEl("div");
    header.style.display = "flex";
    header.style.justifyContent = "space-between";
    header.style.alignItems = "center";
    header.style.cursor = "pointer";
    header.style.padding = "10px";
    header.style.backgroundColor = "var(--background-secondary)";
    header.style.border = "1px solid var(--border-color)";
    header.style.borderRadius = "4px";
    header.style.color = "var(--text-normal)";
    const title = header.createEl("h3", { text: "\u8BF7\u6C42\u4FE1\u606F (\u70B9\u51FB\u5C55\u5F00)" });
    title.style.margin = "0";
    title.style.fontSize = "14px";
    title.style.color = "var(--text-normal)";
    const toggle = header.createEl("span", { text: "\u25BC" });
    toggle.style.color = "var(--text-muted)";
    const content = requestInfoContainer.createEl("div");
    content.style.display = "none";
    content.style.padding = "10px";
    content.style.backgroundColor = "var(--background-secondary)";
    content.style.border = "1px solid var(--border-color)";
    content.style.borderTop = "none";
    content.style.borderRadius = "0 0 4px 4px";
    content.style.color = "var(--text-normal)";
    header.addEventListener("click", () => {
      if (content.style.display === "none") {
        content.style.display = "block";
        toggle.textContent = "\u25B2";
        title.textContent = "\u8BF7\u6C42\u4FE1\u606F (\u70B9\u51FB\u6536\u8D77)";
      } else {
        content.style.display = "none";
        toggle.textContent = "\u25BC";
        title.textContent = "\u8BF7\u6C42\u4FE1\u606F (\u70B9\u51FB\u5C55\u5F00)";
      }
    });
    if (this.imageInfo) {
      const imageInfoHeader = content.createEl("h4", { text: "\u56FE\u7247\u8DEF\u5F84\u4FE1\u606F:" });
      imageInfoHeader.style.color = "var(--text-normal)";
      const imageInfoEl = content.createEl("pre", {
        text: this.imageInfo
      });
      imageInfoEl.style.fontFamily = "monospace";
      imageInfoEl.style.fontSize = "12px";
      imageInfoEl.style.backgroundColor = "var(--background-primary)";
      imageInfoEl.style.border = "1px solid var(--border-color)";
      imageInfoEl.style.padding = "8px";
      imageInfoEl.style.borderRadius = "4px";
      imageInfoEl.style.marginBottom = "10px";
      imageInfoEl.style.whiteSpace = "pre-wrap";
      imageInfoEl.style.wordBreak = "break-all";
      imageInfoEl.style.color = "var(--text-normal)";
    }
    if (this.usedPrompt) {
      const promptHeader = content.createEl("h4", { text: "\u4F7F\u7528\u7684\u63D0\u793A\u8BCD:" });
      promptHeader.style.color = "var(--text-normal)";
      const promptTextArea = content.createEl("textarea", {
        cls: "ankify-debug-prompt",
        text: this.usedPrompt
      });
      promptTextArea.style.width = "100%";
      promptTextArea.style.minHeight = "80px";
      promptTextArea.style.fontFamily = "monospace";
      promptTextArea.style.fontSize = "12px";
      promptTextArea.style.backgroundColor = "var(--background-primary)";
      promptTextArea.style.border = "1px solid var(--border-color)";
      promptTextArea.style.padding = "8px";
      promptTextArea.style.borderRadius = "4px";
      promptTextArea.style.marginBottom = "10px";
      promptTextArea.style.color = "var(--text-normal)";
      promptTextArea.readOnly = true;
    }
    if (this.selectedContent) {
      const contentHeader = content.createEl("h4", { text: "\u9009\u4E2D\u7684\u5185\u5BB9:" });
      contentHeader.style.color = "var(--text-normal)";
      const contentTextArea = content.createEl("textarea", {
        cls: "ankify-debug-content",
        text: this.selectedContent
      });
      contentTextArea.style.width = "100%";
      contentTextArea.style.minHeight = "100px";
      contentTextArea.style.fontFamily = "monospace";
      contentTextArea.style.fontSize = "12px";
      contentTextArea.style.backgroundColor = "var(--background-primary)";
      contentTextArea.style.border = "1px solid var(--border-color)";
      contentTextArea.style.padding = "8px";
      contentTextArea.style.borderRadius = "4px";
      contentTextArea.style.marginBottom = "10px";
      contentTextArea.style.color = "var(--text-normal)";
      contentTextArea.readOnly = true;
    }
    if (Object.keys(this.plugin.noteTypeFields).length > 0) {
      const noteTypeHeader = content.createEl("h4", { text: "\u7B14\u8BB0\u7C7B\u578B\u5B57\u6BB5\u4FE1\u606F:" });
      noteTypeHeader.style.color = "var(--text-normal)";
      const noteTypeFieldsEl = content.createEl("pre", {
        text: Object.entries(this.plugin.noteTypeFields).map(([noteType, fields]) => `${noteType}: ${fields.join(", ")}`).join("\n")
      });
      noteTypeFieldsEl.style.fontFamily = "monospace";
      noteTypeFieldsEl.style.fontSize = "12px";
      noteTypeFieldsEl.style.backgroundColor = "var(--background-primary)";
      noteTypeFieldsEl.style.border = "1px solid var(--border-color)";
      noteTypeFieldsEl.style.padding = "8px";
      noteTypeFieldsEl.style.borderRadius = "4px";
      noteTypeFieldsEl.style.marginBottom = "10px";
      noteTypeFieldsEl.style.whiteSpace = "pre-wrap";
      noteTypeFieldsEl.style.wordBreak = "break-all";
      noteTypeFieldsEl.style.color = "var(--text-normal)";
    }
    if (this.rawResult) {
      const rawResultHeader = content.createEl("h4", { text: "\u5927\u6A21\u578B\u63A5\u53E3\u539F\u59CB\u8FD4\u56DE\u4FE1\u606F:" });
      rawResultHeader.style.color = "var(--text-normal)";
      const rawResultEl = content.createEl("textarea", {
        cls: "ankify-debug-raw-result",
        text: this.rawResult
      });
      rawResultEl.style.width = "100%";
      rawResultEl.style.minHeight = "150px";
      rawResultEl.style.fontFamily = "monospace";
      rawResultEl.style.fontSize = "12px";
      rawResultEl.style.backgroundColor = "var(--background-primary)";
      rawResultEl.style.border = "1px solid var(--border-color)";
      rawResultEl.style.padding = "8px";
      rawResultEl.style.borderRadius = "4px";
      rawResultEl.style.marginBottom = "10px";
      rawResultEl.style.color = "var(--text-normal)";
      rawResultEl.readOnly = true;
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AnkifySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Ankify \u63D2\u4EF6\u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u57FA\u7840\u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("AI\u6A21\u578B\u9009\u62E9").setDesc("\u9009\u62E9\u7528\u4E8E\u751F\u6210Anki\u5361\u7247\u7684AI\u6A21\u578B").addDropdown((dropdown) => {
      dropdown.addOption("deepseek", "DeepSeek").addOption("openai", "OpenAI").addOption("claude", "Claude").addOption("doubao", "\u8C46\u5305 (Doubao)").addOption("custom", "\u81EA\u5B9A\u4E49API").setValue(this.plugin.settings.apiModel).onChange(async (value) => {
        this.plugin.settings.apiModel = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.apiModel === "deepseek") {
      new import_obsidian.Setting(containerEl).setName("DeepSeek API \u5BC6\u94A5").setDesc("\u8F93\u5165\u60A8\u7684DeepSeek API\u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value;
        await this.plugin.saveSettings();
      }));
      const deepseekUrlSetting = new import_obsidian.Setting(containerEl).setName("DeepSeek API URL").setDesc("\u9009\u62E9\u6216\u8F93\u5165DeepSeek API\u7684URL\u5730\u5740");
      const deepseekUrlContainer = deepseekUrlSetting.settingEl.createDiv();
      deepseekUrlContainer.style.display = "flex";
      deepseekUrlContainer.style.flexDirection = "column";
      deepseekUrlContainer.style.gap = "10px";
      deepseekUrlContainer.style.marginTop = "10px";
      const urlSelect = deepseekUrlContainer.createEl("select");
      urlSelect.style.width = "100%";
      urlSelect.style.padding = "5px";
      urlSelect.style.marginBottom = "5px";
      const urlOptions = [
        { value: "https://api.deepseek.com/v1/chat/completions", label: "DeepSeek \u5B98\u65B9 API (v1)", url: "https://api.deepseek.com/v1/chat/completions" },
        { value: "https://api.deepseek.com/v3/chat", label: "DeepSeek V3 API", url: "https://api.deepseek.com/v3/chat" },
        { value: "custom", label: "\u81EA\u5B9A\u4E49 URL", url: "" }
      ];
      urlOptions.forEach((option) => {
        const opt = urlSelect.createEl("option");
        opt.value = option.value;
        opt.text = `${option.label} - ${option.url || "\u624B\u52A8\u8F93\u5165"}`;
        if (this.plugin.settings.deepseekApiUrl === option.value) {
          opt.selected = true;
        }
      });
      const customUrlInput = deepseekUrlContainer.createEl("input");
      customUrlInput.type = "text";
      customUrlInput.placeholder = "\u8F93\u5165\u81EA\u5B9A\u4E49API URL";
      customUrlInput.style.width = "100%";
      customUrlInput.style.padding = "5px";
      customUrlInput.style.display = this.plugin.settings.deepseekApiUrl === "custom" || !urlOptions.some((opt) => opt.value === this.plugin.settings.deepseekApiUrl) ? "block" : "none";
      if (!urlOptions.some((opt) => opt.value === this.plugin.settings.deepseekApiUrl)) {
        customUrlInput.value = this.plugin.settings.deepseekApiUrl;
      }
      urlSelect.addEventListener("change", async () => {
        const selectedValue = urlSelect.value;
        if (selectedValue === "custom") {
          customUrlInput.style.display = "block";
          this.plugin.settings.deepseekApiUrl = customUrlInput.value || "";
        } else {
          customUrlInput.style.display = "none";
          this.plugin.settings.deepseekApiUrl = selectedValue;
        }
        await this.plugin.saveSettings();
      });
      customUrlInput.addEventListener("input", async () => {
        if (urlSelect.value === "custom") {
          this.plugin.settings.deepseekApiUrl = customUrlInput.value;
          await this.plugin.saveSettings();
        }
      });
    } else if (this.plugin.settings.apiModel === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI API \u5BC6\u94A5").setDesc("\u8F93\u5165\u60A8\u7684OpenAI API\u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.apiModel === "claude") {
      new import_obsidian.Setting(containerEl).setName("Claude API \u5BC6\u94A5").setDesc("\u8F93\u5165\u60A8\u7684Claude API\u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.claudeApiKey).onChange(async (value) => {
        this.plugin.settings.claudeApiKey = value;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.apiModel === "custom") {
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49API URL").setDesc("\u8F93\u5165\u81EA\u5B9A\u4E49API\u7684\u5B8C\u6574URL").addText((text) => text.setPlaceholder("https://api.example.com/v1/chat/completions").setValue(this.plugin.settings.customApiUrl).onChange(async (value) => {
        this.plugin.settings.customApiUrl = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49API \u5BC6\u94A5").setDesc("\u8F93\u5165\u81EA\u5B9A\u4E49API\u7684\u5BC6\u94A5").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.customApiKey).onChange(async (value) => {
        this.plugin.settings.customApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49\u6A21\u578B\u540D\u79F0").setDesc("\u8F93\u5165\u8981\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0").addText((text) => text.setPlaceholder("model-name").setValue(this.plugin.settings.customModelName).onChange(async (value) => {
        this.plugin.settings.customModelName = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49API \u7248\u672C (\u53EF\u9009)").setDesc("\u5982\u679C\u9700\u8981\u6307\u5B9AAPI\u7248\u672C\uFF0C\u8BF7\u5728\u6B64\u8F93\u5165").addText((text) => text.setPlaceholder("\u4F8B\u5982\uFF1A2023-06-01").setValue(this.plugin.settings.customApiVersion).onChange(async (value) => {
        this.plugin.settings.customApiVersion = value;
        await this.plugin.saveSettings();
      }));
    } else if (this.plugin.settings.apiModel === "doubao") {
      new import_obsidian.Setting(containerEl).setName("\u8C46\u5305 API \u5BC6\u94A5").setDesc("\u8F93\u5165\u60A8\u7684\u8C46\u5305 API \u5BC6\u94A5").addText((text) => text.setPlaceholder("\u8F93\u5165\u8C46\u5305 API \u5BC6\u94A5").setValue(this.plugin.settings.doubaoApiKey).onChange(async (value) => {
        this.plugin.settings.doubaoApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u8C46\u5305 API URL").setDesc("\u8F93\u5165\u8C46\u5305 API \u7684 URL \u5730\u5740").addText((text) => text.setPlaceholder("https://ark.cn-beijing.volces.com/api/v3/chat/completions").setValue(this.plugin.settings.doubaoApiUrl).onChange(async (value) => {
        this.plugin.settings.doubaoApiUrl = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("\u8C46\u5305\u6A21\u578B\u540D\u79F0").setDesc("\u8F93\u5165\u8981\u4F7F\u7528\u7684\u8C46\u5305\u6A21\u578B\u540D\u79F0").addText((text) => text.setPlaceholder("doubao-1-5-vision-pro-32k-250115").setValue(this.plugin.settings.doubaoModelName).onChange(async (value) => {
        this.plugin.settings.doubaoModelName = value;
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("\u6587\u672C\u5185\u5BB9Prompt").setDesc("\u8BBE\u7F6E\u751F\u6210Anki\u5361\u7247\u7684\u63D0\u793A\u8BCD\uFF08\u7528\u4E8E\u6587\u672C\u5185\u5BB9\uFF09").addTextArea((text) => text.setPlaceholder('\u8BF7\u57FA\u4E8E\u4EE5\u4E0B\u5185\u5BB9\u521B\u5EFAAnki\u5361\u7247\uFF0C\u683C\u5F0F\u4E3A"\u95EE\u9898:::\u7B54\u6848"...').setValue(this.plugin.settings.customPrompt).onChange(async (value) => {
      this.plugin.settings.customPrompt = value;
      await this.plugin.saveSettings();
    }).inputEl.style.minHeight = "80px");
    new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u8BC6\u522BPrompt").setDesc("\u8BBE\u7F6E\u8BC6\u522B\u56FE\u7247\u5185\u5BB9\u5E76\u751F\u6210Anki\u5361\u7247\u7684\u63D0\u793A\u8BCD").addTextArea((text) => text.setPlaceholder("\u8BF7\u8BC6\u522B\u8FD9\u5F20\u56FE\u7247\u4E2D\u7684\u5185\u5BB9\uFF0C\u5E76\u57FA\u4E8E\u56FE\u7247\u5185\u5BB9\u521B\u5EFAAnki\u5361\u7247...").setValue(this.plugin.settings.visionPrompt).onChange(async (value) => {
      this.plugin.settings.visionPrompt = value;
      await this.plugin.saveSettings();
    }).inputEl.style.minHeight = "80px");
    const apiTestSetting = new import_obsidian.Setting(containerEl).setName("API\u8FDE\u901A\u6027\u6D4B\u8BD5").setDesc("\u6D4B\u8BD5\u5F53\u524D\u9009\u62E9\u7684API\u662F\u5426\u53EF\u4EE5\u6B63\u5E38\u8FDE\u63A5");
    const apiTestContainer = apiTestSetting.settingEl.createDiv();
    apiTestContainer.style.display = "flex";
    apiTestContainer.style.alignItems = "center";
    apiTestContainer.style.gap = "10px";
    apiTestContainer.style.marginTop = "10px";
    const apiTestButton = apiTestContainer.createEl("button", {
      text: "\u6D4B\u8BD5API\u8FDE\u63A5"
    });
    const apiTestStatus = apiTestContainer.createEl("span");
    apiTestStatus.style.fontSize = "20px";
    const apiTestResult = containerEl.createEl("div");
    apiTestResult.style.marginTop = "10px";
    apiTestResult.style.padding = "10px";
    apiTestResult.style.backgroundColor = "#f5f5f5";
    apiTestResult.style.border = "1px solid #ddd";
    apiTestResult.style.borderRadius = "4px";
    apiTestResult.style.fontFamily = "monospace";
    apiTestResult.style.fontSize = "12px";
    apiTestResult.style.display = "none";
    apiTestButton.addEventListener("click", async () => {
      apiTestButton.disabled = true;
      apiTestButton.textContent = "\u6D4B\u8BD5\u4E2D...";
      apiTestStatus.textContent = "";
      apiTestResult.textContent = "";
      apiTestResult.style.display = "none";
      try {
        const testResult = await this.plugin.callModelAPI("\u6D4B\u8BD5\u8FDE\u63A5");
        apiTestStatus.textContent = "\u2705";
        apiTestStatus.style.color = "green";
        apiTestResult.textContent = `\u8FDE\u63A5\u6210\u529F\uFF01

API\u8FD4\u56DE\u793A\u4F8B:
${testResult.substring(0, 200)}...`;
        apiTestResult.style.display = "block";
        new import_obsidian.Notice("API\u8FDE\u63A5\u6D4B\u8BD5\u6210\u529F");
      } catch (error) {
        apiTestStatus.textContent = "\u274C";
        apiTestStatus.style.color = "red";
        apiTestResult.textContent = `\u8FDE\u63A5\u5931\u8D25\uFF1A
${error.message}`;
        apiTestResult.style.display = "block";
        new import_obsidian.Notice("API\u8FDE\u63A5\u6D4B\u8BD5\u5931\u8D25");
      } finally {
        apiTestButton.disabled = false;
        apiTestButton.textContent = "\u6D4B\u8BD5API\u8FDE\u63A5";
      }
    });
    const visionTestSetting = new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u8BC6\u522B\u6D4B\u8BD5").setDesc("\u9009\u62E9\u56FE\u7247\u6587\u4EF6\u8FDB\u884C\u6D4B\u8BD5");
    const visionTestContainer = visionTestSetting.settingEl.createDiv();
    visionTestContainer.style.marginTop = "10px";
    const visionTestFileInput = visionTestContainer.createEl("input", {
      type: "file",
      attr: {
        accept: "image/*"
      }
    });
    visionTestFileInput.style.marginBottom = "10px";
    const visionTestButtonContainer = visionTestContainer.createDiv();
    visionTestButtonContainer.style.display = "flex";
    visionTestButtonContainer.style.alignItems = "center";
    visionTestButtonContainer.style.gap = "10px";
    visionTestButtonContainer.style.marginTop = "10px";
    const visionTestButton = visionTestButtonContainer.createEl("button", {
      text: "\u6D4B\u8BD5\u56FE\u7247\u8BC6\u522B"
    });
    const visionTestStatus = visionTestButtonContainer.createEl("span");
    visionTestStatus.style.fontSize = "20px";
    const visionTestResult = containerEl.createEl("textarea");
    visionTestResult.placeholder = "\u8BC6\u522B\u7ED3\u679C\u5C06\u663E\u793A\u5728\u8FD9\u91CC...";
    visionTestResult.style.width = "100%";
    visionTestResult.style.minHeight = "150px";
    visionTestResult.style.marginTop = "10px";
    visionTestResult.style.padding = "10px";
    visionTestResult.style.backgroundColor = "#f5f5f5";
    visionTestResult.style.border = "1px solid #ddd";
    visionTestResult.style.borderRadius = "4px";
    visionTestResult.style.fontFamily = "monospace";
    visionTestResult.style.fontSize = "12px";
    visionTestResult.style.display = "none";
    visionTestResult.readOnly = true;
    visionTestButton.addEventListener("click", async () => {
      var _a;
      const file = (_a = visionTestFileInput.files) == null ? void 0 : _a[0];
      if (!file) {
        new import_obsidian.Notice("\u8BF7\u5148\u9009\u62E9\u56FE\u7247\u6587\u4EF6");
        return;
      }
      visionTestButton.disabled = true;
      visionTestButton.textContent = "\u8BC6\u522B\u4E2D...";
      visionTestStatus.textContent = "";
      visionTestResult.textContent = "";
      visionTestResult.style.display = "none";
      try {
        console.log("\u5F00\u59CB\u8BFB\u53D6\u56FE\u7247:", file.name, "\u5927\u5C0F:", file.size);
        console.log("\u4F7F\u7528\u7684Prompt:", this.plugin.settings.visionPrompt);
        const reader = new FileReader();
        const base64Image = await new Promise((resolve, reject) => {
          reader.onload = () => {
            const result2 = reader.result;
            resolve(result2);
          };
          reader.onerror = () => reject(reader.error);
          reader.readAsDataURL(file);
        });
        console.log("Base64\u8F6C\u6362\u6210\u529F\uFF0C\u5927\u5C0F:", Math.round(base64Image.length / 1024), "KB");
        const compressedImage = await this.plugin.compressImage(base64Image);
        console.log("\u56FE\u7247\u538B\u7F29\u5B8C\u6210");
        const result = await this.plugin.callVisionAPI(compressedImage);
        visionTestStatus.textContent = "\u2705";
        visionTestStatus.style.color = "green";
        const resultText = `\u3010\u4F7F\u7528\u7684Prompt\u3011
${this.plugin.settings.visionPrompt}

${"=".repeat(50)}

\u3010\u8BC6\u522B\u7ED3\u679C\u3011
${result}`;
        visionTestResult.textContent = resultText;
        visionTestResult.style.display = "block";
        new import_obsidian.Notice("\u56FE\u7247\u8BC6\u522B\u6D4B\u8BD5\u6210\u529F");
      } catch (error) {
        console.error("\u56FE\u7247\u8BC6\u522B\u6D4B\u8BD5\u5931\u8D25:", error);
        visionTestStatus.textContent = "\u274C";
        visionTestStatus.style.color = "red";
        visionTestResult.textContent = `\u8BC6\u522B\u5931\u8D25\uFF1A
${error.message}`;
        visionTestResult.style.display = "block";
        new import_obsidian.Notice("\u56FE\u7247\u8BC6\u522B\u6D4B\u8BD5\u5931\u8D25");
      } finally {
        visionTestButton.disabled = false;
        visionTestButton.textContent = "\u6D4B\u8BD5\u56FE\u7247\u8BC6\u522B";
      }
    });
    containerEl.createEl("h3", { text: "\u56FE\u7247\u8BC6\u522B\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u6700\u5927\u5C3A\u5BF8").setDesc("\u56FE\u7247\u8BC6\u522B\u524D\u4F1A\u538B\u7F29\u5230\u6B64\u5C3A\u5BF8\uFF08\u50CF\u7D20\uFF09\uFF0C\u51CF\u5C11token\u6D88\u8017\u3002\u63A8\u8350\uFF1A512-1024").addText((text) => text.setPlaceholder("1024").setValue(String(this.plugin.settings.maxImageSize)).onChange(async (value) => {
      const size = parseInt(value);
      if (!isNaN(size) && size > 0) {
        this.plugin.settings.maxImageSize = size;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u538B\u7F29\u8D28\u91CF").setDesc("\u56FE\u7247\u538B\u7F29\u8D28\u91CF\uFF080.1-1.0\uFF09\uFF0C\u8D8A\u4F4E\u6587\u4EF6\u8D8A\u5C0F\u4F46\u8D28\u91CF\u8D8A\u5DEE\u3002\u63A8\u8350\uFF1A0.7-0.9").addText((text) => text.setPlaceholder("0.8").setValue(String(this.plugin.settings.imageQuality)).onChange(async (value) => {
      const quality = parseFloat(value);
      if (!isNaN(quality) && quality >= 0.1 && quality <= 1) {
        this.plugin.settings.imageQuality = quality;
        await this.plugin.saveSettings();
      }
    }));
    containerEl.createEl("h3", { text: "Anki Connect \u8BBE\u7F6E" });
    const ankiConnectSetting = new import_obsidian.Setting(containerEl).setName("Anki Connect URL").setDesc("Anki Connect API\u7684\u5730\u5740\uFF0C\u9ED8\u8BA4\u4E3A http://127.0.0.1:8765");
    const ankiConnectContainer = ankiConnectSetting.settingEl.createDiv();
    ankiConnectContainer.style.display = "flex";
    ankiConnectContainer.style.alignItems = "center";
    ankiConnectContainer.style.gap = "10px";
    ankiConnectContainer.style.marginTop = "10px";
    const urlInput = ankiConnectContainer.createEl("input");
    urlInput.type = "text";
    urlInput.placeholder = "http://127.0.0.1:8765";
    urlInput.value = this.plugin.settings.ankiConnectUrl;
    urlInput.style.flex = "1";
    urlInput.style.padding = "5px";
    urlInput.addEventListener("change", async () => {
      this.plugin.settings.ankiConnectUrl = urlInput.value;
      await this.plugin.saveSettings();
    });
    const testButton = ankiConnectContainer.createEl("button");
    testButton.textContent = "\u6D4B\u8BD5\u8FDE\u63A5";
    testButton.addEventListener("click", async () => {
      testButton.disabled = true;
      testButton.textContent = "\u6D4B\u8BD5\u4E2D...";
      try {
        const result = await this.plugin.invokeAnkiConnect("version");
        new import_obsidian.Notice(`Anki Connect \u8FDE\u63A5\u6210\u529F\uFF01\u7248\u672C: ${result}`);
      } catch (error) {
        console.error("Anki Connect \u6D4B\u8BD5\u5931\u8D25:", error);
        new import_obsidian.Notice(`Anki Connect \u8FDE\u63A5\u5931\u8D25: ${error.message}`);
      } finally {
        testButton.disabled = false;
        testButton.textContent = "\u6D4B\u8BD5\u8FDE\u63A5";
      }
    });
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u724C\u7EC4").setDesc("\u6DFB\u52A0\u5361\u7247\u65F6\u7684\u9ED8\u8BA4\u724C\u7EC4\u540D\u79F0").addText((text) => text.setPlaceholder("Default").setValue(this.plugin.settings.defaultDeck).onChange(async (value) => {
      this.plugin.settings.defaultDeck = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u7B14\u8BB0\u7C7B\u578B").setDesc("\u6DFB\u52A0\u5361\u7247\u65F6\u7684\u9ED8\u8BA4\u7B14\u8BB0\u7C7B\u578B").addText((text) => text.setPlaceholder("Basic").setValue(this.plugin.settings.defaultNoteType).onChange(async (value) => {
      this.plugin.settings.defaultNoteType = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u76F4\u63A5\u63D2\u5165\u6587\u6863").setDesc("\u542F\u7528\u540E\uFF0C\u751F\u6210\u7684Anki\u5361\u7247\u5C06\u76F4\u63A5\u63D2\u5165\u5230\u6587\u6863\u672B\u5C3E\uFF0C\u800C\u4E0D\u662F\u663E\u793A\u5728\u5F39\u7A97\u4E2D").addToggle((toggle) => toggle.setValue(this.plugin.settings.insertToDocument).onChange(async (value) => {
      this.plugin.settings.insertToDocument = value;
      await this.plugin.saveSettings();
    }));
  }
};
